/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.quanlitau;

import connectSQL.LopKetNoi;
import controller.ChuyenManHinhView;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.JPanelQuanLiToaTau;
import view.JPanelQuanLiTuyen;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanelDanhSachToa extends javax.swing.JPanel {

    /**
     * Creates new form JPanelToa
     */
    private DefaultTableModel tbmLoaiToa, tbmToa;
    private int hangDangChonLoaiToa = -1;
    private int hangDangChonToa = -1;

    // loai dialog
    private String them = "THÊM";
    private String sua = "SỬA";
    private String thongTin = "THÔNG TIN";

    public JPanelDanhSachToa() {
        initComponents();
        tbmLoaiToa = (DefaultTableModel) jtbLoaiToa.getModel();
        tbmToa = (DefaultTableModel) jtbToa.getModel();
        loadDSLoaiToaVaoBang(LopKetNoi.select("select * from LoaiToa"));
        loadDSToaVaoBang(LopKetNoi.select("select * from Toa"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlLoaiToa = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jlbTenDialogLoaiToa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnXacNhanLoaiToa = new javax.swing.JButton();
        jtfMaLoaiToa = new javax.swing.JTextField();
        jtfHeSo = new javax.swing.JTextField();
        jlbMaLoaiToa = new javax.swing.JLabel();
        jlbHeSo = new javax.swing.JLabel();
        jdlToa = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jlbTenDialogToa = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfMaToa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfSoChoNgoi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbbLoaiToa = new javax.swing.JComboBox<>();
        btnXacNhanToa = new javax.swing.JButton();
        jlbMaToa = new javax.swing.JLabel();
        jlbSoChoNgoi = new javax.swing.JLabel();
        jtfHeSoLoaiToa = new javax.swing.JTextField();
        jlbLoaiToa = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnToa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbToa = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnThemToa = new javax.swing.JButton();
        btnSuaToa = new javax.swing.JButton();
        btnXoaToa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfTimKiemToa = new javax.swing.JTextField();
        cbbTimKiemToa = new javax.swing.JComboBox<>();
        cbbSapXepToa = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnTroVeToa = new javax.swing.JButton();
        btnThongTinToa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jpnLoaiToa = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jtbLoaiToa = new javax.swing.JTable();
        jLabel50 = new javax.swing.JLabel();
        btnThemLoaiToa = new javax.swing.JButton();
        btnSuaLoaiToa = new javax.swing.JButton();
        btnXoaLoaiToa = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jtfTimKiemLoaiToa = new javax.swing.JTextField();
        cbbTimKiemLoaiToa = new javax.swing.JComboBox<>();
        cbbSapXepLoaiToa = new javax.swing.JComboBox<>();
        jLabel52 = new javax.swing.JLabel();
        btnTroVeLoaiToa = new javax.swing.JButton();
        btnThongTinLoaiToa = new javax.swing.JButton();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();

        jdlLoaiToa.setMinimumSize(new java.awt.Dimension(408, 290));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlbTenDialogLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlbTenDialogLoaiToa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenDialogLoaiToa.setText("THÊM LOẠI TOA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("MÃ LOẠI:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("HỆ SỐ:");

        btnXacNhanLoaiToa.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnXacNhanLoaiToa.setText("XÁC NHẬN");
        btnXacNhanLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanLoaiToaActionPerformed(evt);
            }
        });

        jtfMaLoaiToa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtfHeSo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlbMaLoaiToa.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbMaLoaiToa.setForeground(new java.awt.Color(255, 0, 0));
        jlbMaLoaiToa.setText("A ");

        jlbHeSo.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbHeSo.setForeground(new java.awt.Color(255, 0, 0));
        jlbHeSo.setText("a");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTenDialogLoaiToa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbMaLoaiToa, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jtfMaLoaiToa)
                    .addComponent(jtfHeSo)
                    .addComponent(jlbHeSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(btnXacNhanLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlbTenDialogLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfMaLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMaLoaiToa)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbHeSo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnXacNhanLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jdlLoaiToaLayout = new javax.swing.GroupLayout(jdlLoaiToa.getContentPane());
        jdlLoaiToa.getContentPane().setLayout(jdlLoaiToaLayout);
        jdlLoaiToaLayout.setHorizontalGroup(
            jdlLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlLoaiToaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdlLoaiToaLayout.setVerticalGroup(
            jdlLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlLoaiToaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jdlToa.setMinimumSize(new java.awt.Dimension(430, 403));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jlbTenDialogToa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbTenDialogToa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenDialogToa.setText("TOA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("MÃ TOA:");

        jtfMaToa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("SỐ CHỖ NGỒI:");

        jtfSoChoNgoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfSoChoNgoi.setText("20");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("LOẠI TOA:");

        cbbLoaiToa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbLoaiToa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiToaActionPerformed(evt);
            }
        });

        btnXacNhanToa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXacNhanToa.setText("XÁC NHẬN");
        btnXacNhanToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanToaActionPerformed(evt);
            }
        });

        jlbMaToa.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbMaToa.setForeground(new java.awt.Color(255, 0, 0));
        jlbMaToa.setText(" ");

        jlbSoChoNgoi.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbSoChoNgoi.setForeground(new java.awt.Color(255, 0, 0));
        jlbSoChoNgoi.setText(" ");

        jtfHeSoLoaiToa.setEditable(false);
        jtfHeSoLoaiToa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfHeSoLoaiToa.setToolTipText("HỆ SỐ");

        jlbLoaiToa.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbLoaiToa.setForeground(new java.awt.Color(255, 0, 0));
        jlbLoaiToa.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTenDialogToa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXacNhanToa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSoChoNgoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfMaToa)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbbLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfHeSoLoaiToa, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addComponent(jlbMaToa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfSoChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbLoaiToa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jlbTenDialogToa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfMaToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMaToa)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfSoChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbSoChoNgoi)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfHeSoLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbLoaiToa)
                .addGap(16, 16, 16)
                .addComponent(btnXacNhanToa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdlToaLayout = new javax.swing.GroupLayout(jdlToa.getContentPane());
        jdlToa.getContentPane().setLayout(jdlToaLayout);
        jdlToaLayout.setHorizontalGroup(
            jdlToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlToaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdlToaLayout.setVerticalGroup(
            jdlToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlToaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jpnToa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH TOA");

        jtbToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbToa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ TOA", "SỐ CHỖ NGỒI", "MÃ LOẠI TOA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbToa.setGridColor(new java.awt.Color(255, 255, 255));
        jtbToa.setRowHeight(25);
        jtbToa.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jtbToa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbToaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbToaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbToa);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Chức năng");

        btnThemToa.setBackground(new java.awt.Color(255, 255, 255));
        btnThemToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemToa.setText("THÊM");
        btnThemToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemToaActionPerformed(evt);
            }
        });

        btnSuaToa.setBackground(new java.awt.Color(255, 255, 255));
        btnSuaToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaToa.setText("SỬA");
        btnSuaToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaToaActionPerformed(evt);
            }
        });

        btnXoaToa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaToa.setText("XÓA");
        btnXoaToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaToaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tìm kiếm:");

        jtfTimKiemToa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemToaKeyReleased(evt);
            }
        });

        cbbTimKiemToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbTimKiemToa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã toa", "Số chỗ ngồi", "Loại toa" }));

        cbbSapXepToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbSapXepToa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã toa a-z", "Số chỗ ngồi tăng", "Loại toa a-z" }));
        cbbSapXepToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSapXepToaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Sắp xếp:");

        btnTroVeToa.setBackground(new java.awt.Color(255, 255, 255));
        btnTroVeToa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        btnTroVeToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeToaActionPerformed(evt);
            }
        });

        btnThongTinToa.setBackground(new java.awt.Color(255, 255, 255));
        btnThongTinToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongTinToa.setText("THÔNG TIN");
        btnThongTinToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinToaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnToaLayout = new javax.swing.GroupLayout(jpnToa);
        jpnToa.setLayout(jpnToaLayout);
        jpnToaLayout.setHorizontalGroup(
            jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnToaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnToaLayout.createSequentialGroup()
                        .addComponent(btnTroVeToa)
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnToaLayout.createSequentialGroup()
                        .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnToaLayout.createSequentialGroup()
                                .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpnToaLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(59, 59, 59)
                                        .addComponent(btnThemToa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(btnSuaToa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(btnXoaToa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpnToaLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfTimKiemToa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbTimKiemToa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbSapXepToa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThongTinToa, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 37, Short.MAX_VALUE))))
        );
        jpnToaLayout.setVerticalGroup(
            jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnToaLayout.createSequentialGroup()
                .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnToaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnTroVeToa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnToaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnThemToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongTinToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbSapXepToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtfTimKiemToa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbbTimKiemToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("TOA", jpnToa);

        jpnLoaiToa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setText("DANH SÁCH LOẠI TOA");

        jtbLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbLoaiToa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ LOẠI TOA", "HỆ SỐ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbLoaiToa.setGridColor(new java.awt.Color(255, 255, 255));
        jtbLoaiToa.setRowHeight(25);
        jtbLoaiToa.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jtbLoaiToa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbLoaiToaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbLoaiToaMousePressed(evt);
            }
        });
        jScrollPane13.setViewportView(jtbLoaiToa);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setText("Chức năng");

        btnThemLoaiToa.setBackground(new java.awt.Color(255, 255, 255));
        btnThemLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemLoaiToa.setText("THÊM");
        btnThemLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiToaActionPerformed(evt);
            }
        });

        btnSuaLoaiToa.setBackground(new java.awt.Color(255, 255, 255));
        btnSuaLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaLoaiToa.setText("SỬA");
        btnSuaLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLoaiToaActionPerformed(evt);
            }
        });

        btnXoaLoaiToa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaLoaiToa.setText("XÓA");
        btnXoaLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoaiToaActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setText("Tìm kiếm:");

        jtfTimKiemLoaiToa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemLoaiToaKeyReleased(evt);
            }
        });

        cbbTimKiemLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbTimKiemLoaiToa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã loại toa", "hệ số" }));

        cbbSapXepLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbSapXepLoaiToa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã a-z", "Hệ số tăng", "Hệ số giảm" }));
        cbbSapXepLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSapXepLoaiToaActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setText("Sắp xếp:");

        btnTroVeLoaiToa.setBackground(new java.awt.Color(255, 255, 255));
        btnTroVeLoaiToa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        btnTroVeLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeLoaiToaActionPerformed(evt);
            }
        });

        btnThongTinLoaiToa.setBackground(new java.awt.Color(255, 255, 255));
        btnThongTinLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongTinLoaiToa.setText("THÔNG TIN");
        btnThongTinLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinLoaiToaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnLoaiToaLayout = new javax.swing.GroupLayout(jpnLoaiToa);
        jpnLoaiToa.setLayout(jpnLoaiToaLayout);
        jpnLoaiToaLayout.setHorizontalGroup(
            jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                        .addComponent(btnTroVeLoaiToa)
                        .addGap(241, 241, 241)
                        .addComponent(jLabel49)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                        .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator26)
                            .addComponent(jSeparator25)
                            .addComponent(jScrollPane13)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoaiToaLayout.createSequentialGroup()
                                .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                                        .addComponent(jLabel50)
                                        .addGap(59, 59, 59)
                                        .addComponent(btnThemLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(btnSuaLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(btnXoaLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                                        .addComponent(jLabel51)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfTimKiemLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbTimKiemLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel52)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbSapXepLoaiToa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThongTinLoaiToa, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 37, Short.MAX_VALUE))))
        );
        jpnLoaiToaLayout.setVerticalGroup(
            jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnTroVeLoaiToa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoaiToaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel49)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(btnThemLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongTinLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbSapXepLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(jtfTimKiemLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(cbbTimKiemLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("LOẠI TOA", jpnLoaiToa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtbToaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbToaMouseClicked
        // TODO add your handling code here:
        hangDangChonToa = jtbToa.getSelectedRow();
    }//GEN-LAST:event_jtbToaMouseClicked

    private void jtbToaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbToaMousePressed
        // TODO add your handling code here:
        hangDangChonToa = jtbToa.getSelectedRow();
        if (hangDangChonToa != -1) {
            if (evt.getButton() == MouseEvent.BUTTON3) {
                hienThiDialogToa(thongTin);
            }
        }
    }//GEN-LAST:event_jtbToaMousePressed

    private void btnThemToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemToaActionPerformed
        // TODO add your handling code here:
        hienThiDialogToa(them);
    }//GEN-LAST:event_btnThemToaActionPerformed

    private void btnSuaToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaToaActionPerformed
        // TODO add your handling code here:
        if (hangDangChonToa < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 dòng trong bảng");
        } else {
            hienThiDialogToa(sua);
        }
    }//GEN-LAST:event_btnSuaToaActionPerformed

    private void btnXoaToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaToaActionPerformed
        // TODO add your handling code here:
        if (hangDangChonToa < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 hàng trong bảng");

        } else {
            int input = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (input == JOptionPane.YES_OPTION) {
                String maToa = jtbToa.getValueAt(hangDangChonToa, 0).toString();
                if (LopKetNoi.update("delete from Toa where maToa = ?", maToa)) {
                    tbmToa.removeRow(hangDangChonToa);
                    hangDangChonToa = -1;
                    jtbToa.clearSelection();
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể xóa vì có tàu đang chứa toa");
                }
            }

        }
    }//GEN-LAST:event_btnXoaToaActionPerformed

    private void jtfTimKiemToaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemToaKeyReleased
        // TODO add your handling code here:

        if (cbbTimKiemToa.getSelectedIndex() == 0) {// tim kiem theo ma toa
            String maToa = jtfTimKiemToa.getText().trim();
            loadDSToaVaoBang(LopKetNoi.select("select * from Toa where maToa like ?", "%" + maToa + "%"));
        } else if (cbbTimKiemToa.getSelectedIndex() == 1) {// tim kiem theo so cho ngoi
            if (jtfTimKiemToa.getText().trim().equals("")) {
                loadDSToaVaoBang(LopKetNoi.select("select * from Toa"));
            } else {
                try {
                    int soChoNgoi = Integer.parseInt(jtfTimKiemToa.getText().trim());
                    loadDSToaVaoBang(LopKetNoi.select("select * from Toa where soChoNgoi = ?", soChoNgoi));
                } catch (Exception e) {
                    // khong lam gi het
                }
            }

        } else if (cbbTimKiemToa.getSelectedIndex() == 2) {// tim kiem theo loai toa
            String maLoaiToa = jtfTimKiemToa.getText().trim();
            loadDSToaVaoBang(LopKetNoi.select("select * from Toa where maLoaiToa like ?", "%" + maLoaiToa + "%"));
        }
    }//GEN-LAST:event_jtfTimKiemToaKeyReleased

    private void cbbSapXepToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSapXepToaActionPerformed
        // TODO add your handling code here:
        if (cbbSapXepToa.getSelectedIndex() == 0) {// sap xep ma toa tu a - z
            loadDSToaVaoBang(LopKetNoi.select("select * from Toa order by maToa ASC ?"));
        } else if (cbbSapXepToa.getSelectedIndex() == 1) {// sap xep theo so cho ngoi tang
            loadDSToaVaoBang(LopKetNoi.select("select * from Toa order by soChoNgoi ASC ?"));
        } else if (cbbSapXepToa.getSelectedIndex() == 2) {// sap xep theo loai toa a-z
            loadDSToaVaoBang(LopKetNoi.select("select * from Toa order by maLoaiToa ASC ?"));
        }
    }//GEN-LAST:event_cbbSapXepToaActionPerformed

    private void btnTroVeToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeToaActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiToaTau()).change();
    }//GEN-LAST:event_btnTroVeToaActionPerformed

    private void btnThongTinToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinToaActionPerformed
        // TODO add your handling code here:
        if (hangDangChonToa == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hàng trong bảng");
        } else
            hienThiDialogToa(thongTin);
    }//GEN-LAST:event_btnThongTinToaActionPerformed

    private void jtbLoaiToaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbLoaiToaMouseClicked
        // TODO add your handling code here:
        hangDangChonLoaiToa = jtbLoaiToa.getSelectedRow();
    }//GEN-LAST:event_jtbLoaiToaMouseClicked

    private void jtbLoaiToaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbLoaiToaMousePressed
        // TODO add your handling code here:
        hangDangChonLoaiToa = jtbLoaiToa.getSelectedRow();
        if (hangDangChonLoaiToa != -1) {
            if (evt.getButton() == MouseEvent.BUTTON3) {
                hienThiDialogLoaiToa(thongTin);
            }
        }
    }//GEN-LAST:event_jtbLoaiToaMousePressed

    private void btnThemLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiToaActionPerformed
        // TODO add your handling code here:
        hienThiDialogLoaiToa(them);
    }//GEN-LAST:event_btnThemLoaiToaActionPerformed

    private void btnSuaLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLoaiToaActionPerformed
        // TODO add your handling code here:
        if (hangDangChonLoaiToa < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 dòng trong bảng");
        } else {
            hienThiDialogLoaiToa(sua);
        }
    }//GEN-LAST:event_btnSuaLoaiToaActionPerformed

    private void btnXoaLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoaiToaActionPerformed
        // TODO add your handling code here:
        if (hangDangChonLoaiToa < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 hàng trong bảng");

        } else {
            int input = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (input == JOptionPane.YES_OPTION) {
                String maLoaiToa = jtbLoaiToa.getValueAt(hangDangChonLoaiToa, 0).toString();

                if (LopKetNoi.update("delete from LoaiToa where maLoaiToa = ?", maLoaiToa)) {
                    tbmLoaiToa.removeRow(hangDangChonLoaiToa);
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    hangDangChonLoaiToa = -1;
                    jtbLoaiToa.clearSelection();
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể xóa vì loại toa đang thuộc toa");
                }

            }
        }
    }//GEN-LAST:event_btnXoaLoaiToaActionPerformed

    private void jtfTimKiemLoaiToaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemLoaiToaKeyReleased
        // TODO add your handling code here:

        if (cbbTimKiemLoaiToa.getSelectedIndex() == 0) {// tim kiem theo ma loai toa
            String maLoaiToa = jtfTimKiemLoaiToa.getText().trim();
            loadDSLoaiToaVaoBang(LopKetNoi.select("select * from LoaiToa where maLoaiToa like ?",
                    "%" + maLoaiToa + "%"));
        } else {// tim kiem theo ten tuyen
            try {
                if (jtfTimKiemLoaiToa.getText().trim().equals("")) {
                    loadDSLoaiToaVaoBang(LopKetNoi.select("select * from LoaiToa"));
                } else {
                    Float heSo = Float.parseFloat(jtfTimKiemLoaiToa.getText().trim());

                    loadDSLoaiToaVaoBang(LopKetNoi.select("select * from LoaiToa where heSo = ?",
                            heSo));
                }
            } catch (Exception e) {
            }

        }
        hangDangChonLoaiToa = -1;
    }//GEN-LAST:event_jtfTimKiemLoaiToaKeyReleased

    private void cbbSapXepLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSapXepLoaiToaActionPerformed
        // TODO add your handling code here:
        if (cbbSapXepLoaiToa.getSelectedIndex() == 0) {// sap xep ma loai toa tu a - z
            loadDSLoaiToaVaoBang(LopKetNoi.select("select * from LoaiToa order by maLoaiToa ASC"));
        } else if (cbbSapXepLoaiToa.getSelectedIndex() == 1) {
            loadDSLoaiToaVaoBang(LopKetNoi.select("select * from LoaiToa order by heSo ASC"));
        } else {
            loadDSLoaiToaVaoBang(LopKetNoi.select("select * from LoaiToa order by heSo DESC"));
        }
        hangDangChonLoaiToa = -1;
    }//GEN-LAST:event_cbbSapXepLoaiToaActionPerformed

    private void btnTroVeLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeLoaiToaActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiToaTau()).change();
    }//GEN-LAST:event_btnTroVeLoaiToaActionPerformed

    private void btnThongTinLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinLoaiToaActionPerformed
        // TODO add your handling code here:
        if (hangDangChonLoaiToa == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hàng trong bảng");
        } else
            hienThiDialogLoaiToa(thongTin);
    }//GEN-LAST:event_btnThongTinLoaiToaActionPerformed

    private void btnXacNhanLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanLoaiToaActionPerformed
        // TODO add your handling code here:
        String loai = jlbTenDialogLoaiToa.getText();
        if (loai.equals(them)) {
            if (themLoaiToa()) {
                JOptionPane.showMessageDialog(jdlLoaiToa, "Thêm thành công");
                jtfHeSo.setText("1");
                jtfMaLoaiToa.setText("");
                jlbHeSo.setText(" ");
                jlbMaLoaiToa.setText(" ");
                hangDangChonLoaiToa = jtbLoaiToa.getRowCount() - 1;
            } else {
                JOptionPane.showMessageDialog(jdlLoaiToa, "Thêm thất bại");
            }
        } else if (loai.equals(sua)) {
            if (suaLoaiToa()) {
                JOptionPane.showMessageDialog(jdlLoaiToa, "Sửa thành công");
                jdlLoaiToa.dispose();
            } else {
                JOptionPane.showMessageDialog(jdlLoaiToa, "Sửa thất bại");
            }

        } else if (loai.equals(thongTin)) {
            jdlLoaiToa.dispose();
        }
    }//GEN-LAST:event_btnXacNhanLoaiToaActionPerformed

    private void cbbLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiToaActionPerformed
        // TODO add your handling code here:
        if (cbbLoaiToa.getItemCount() != 0) {
            ResultSet rs = LopKetNoi.select("select heSo from LoaiToa where maLoaiToa = ?", cbbLoaiToa.getSelectedItem().toString());
            try {
                if (rs.next()) {
                    jtfHeSoLoaiToa.setText(rs.getString(1));
                }
            } catch (SQLException ex) {
                Logger.getLogger(JPanelDanhSachToa.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_cbbLoaiToaActionPerformed

    private void btnXacNhanToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanToaActionPerformed
        // TODO add your handling code here:
        String loai = jlbTenDialogToa.getText();
        if (loai.equals(them)) {
            if (themToa()) {
                JOptionPane.showMessageDialog(jdlToa, "Thêm thành công");
                setRongCacTruongToa();
                tatThongBaoToa();
                hangDangChonToa = jtbToa.getRowCount() - 1;
            } else {
                JOptionPane.showMessageDialog(jdlToa, "Thêm thất bại");
            }
        } else if (loai.equals(sua)) {
            if (suaToa()) {
                JOptionPane.showMessageDialog(jdlToa, "Sửa thành công");
                jdlToa.dispose();
            } else {
                JOptionPane.showMessageDialog(jdlToa, "Sửa thất bại");
            }

        } else if (loai.equals(thongTin)) {
            jdlToa.dispose();
        }
    }//GEN-LAST:event_btnXacNhanToaActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTabbedPane1StateChanged
    //========================================================code cho loai toa===========================================================
    private void loadDSLoaiToaVaoBang(ResultSet rs) {// maloaitoa, he so
        tbmLoaiToa.setRowCount(0);
        jtbLoaiToa.clearSelection();
        try {
            while (rs.next()) {
                tbmLoaiToa.addRow(new Object[]{rs.getString(1), rs.getFloat(2)});
            }
        } catch (Exception e) {
            System.out.println("Load ds laoi toa vao bang that bai");
        }
    }

    private void kiemTraHeSo() {
        if (jtfHeSo.getText().trim().equals("")) {
            jlbHeSo.setText("Không được để trống");
        } else {
            float heSo = 0;
            try {
                heSo = Float.parseFloat(jtfHeSo.getText().trim().toString());
                if (heSo == 0) {
                    jlbHeSo.setText("Hệ số phải lớn hơn 0");
                } else {
                    jlbHeSo.setText(" ");
                }
            } catch (Exception e) {
                jlbHeSo.setText("Hệ số phải là một số");
            }
        }
    }

    private boolean kiemTraThemLoaiToa() {
        String maLoaiToa = jtfMaLoaiToa.getText().trim();
        if (maLoaiToa.equals("")) {
            jlbMaLoaiToa.setText("Không được để trống");
        } else {
            try {
                ResultSet rs = LopKetNoi.select("select maLoaiToa from LoaiToa where maLoaiToa = ?", maLoaiToa);
                if (rs.next()) {
                    jlbMaLoaiToa.setText("Mã loại toa đã tồn tại");
                } else {
                    jlbMaLoaiToa.setText(" ");
                }
            } catch (Exception e) {
                System.out.println("Kieemr tra them loai toa that bai");
            }
        }

        // kiem tra he so
        kiemTraHeSo();

        if (jlbMaLoaiToa.getText().equals(" ") && jlbHeSo.getText().equals(" ")) {
            return true;
        } else {
            return false;
        }
    }

    private boolean themLoaiToa() {
        if (kiemTraThemLoaiToa()) {
            try {
                LopKetNoi.update("insert into LoaiToa values(?,?)", jtfMaLoaiToa.getText().trim(),
                        Float.parseFloat(jtfHeSo.getText().trim()));
                tbmLoaiToa.addRow(new Object[]{jtfMaLoaiToa.getText().trim(),
                    Float.parseFloat(jtfHeSo.getText().trim())});
                // highlight dong cuoi
                int hangCuoi = jtbLoaiToa.getRowCount();
                jtbLoaiToa.scrollRectToVisible(jtbLoaiToa.getCellRect(hangCuoi - 1, 0, true));// di chuyen bang den row cuoi
                jtbLoaiToa.clearSelection();
                jtbLoaiToa.setRowSelectionInterval(hangCuoi - 1, hangCuoi - 1);
                return true;
            } catch (Exception e) {
                System.out.println("Them loai toa that bai");
            }
        }
        return false;
    }

    private boolean suaLoaiToa() {
        kiemTraHeSo();
        if (jlbHeSo.equals(" ")) {
            try {
                LopKetNoi.update("update LoaiToa set heSo = ?", Float.parseFloat(jtfHeSo.getText().trim()));
            } catch (Exception e) {
                System.out.println("Sua loai toa that bai");
            }
        } else {
            return false;
        }
        return true;
    }

    private void thongTinLoaiToa() {
        jtfMaLoaiToa.setText(jtbLoaiToa.getValueAt(hangDangChonLoaiToa, 0) + "");
        jtfHeSo.setText(jtbLoaiToa.getValueAt(hangDangChonLoaiToa, 1) + "");
    }

    private void setRongCacTruongLoaiToa() {
        jtfMaLoaiToa.setText("");
        jtfHeSo.setText("1");
    }

    private void tatThongBaoLoaiToa() {
        jlbMaLoaiToa.setText(" ");
        jlbHeSo.setText(" ");
    }

    private void hienCacTruongLoaiToa() {
        jtfMaLoaiToa.setEditable(true);
        jtfHeSo.setEditable(true);
    }

    private void anCacTruongLoaiToa() {
        jtfMaLoaiToa.setEditable(false);
        jtfHeSo.setEditable(false);
    }

    private void hienThiDialogLoaiToa(String loai) {
        setRongCacTruongLoaiToa();
        hienCacTruongLoaiToa();
        tatThongBaoLoaiToa();
        if (loai.equals(them)) {

        } else if (loai.equals(sua)) {
            jtfMaLoaiToa.setText(jtbLoaiToa.getValueAt(hangDangChonLoaiToa, 0) + "");
            jtfMaLoaiToa.setEditable(false);
            jtfHeSo.setText(jtbLoaiToa.getValueAt(hangDangChonLoaiToa, 1) + "");
        } else if (loai.equals(thongTin)) {
            thongTinLoaiToa();
        }
        jlbTenDialogLoaiToa.setText(loai);
        jdlLoaiToa.setLocationRelativeTo(this);
        jdlLoaiToa.setVisible(true);
    }

    //========================================code cho toa==================================================
    private void loadDSToaVaoBang(ResultSet rs) {// matoa, sochongoi, maloaitoa
        tbmToa.setRowCount(0);
        try {
            while (rs.next()) {
                tbmToa.addRow(new Object[]{rs.getString(1), rs.getInt(2), rs.getString(3)});
            }
        } catch (Exception e) {
            System.out.println("Load ds  toa vao bang that bai");
        }
    }

    private void loadDSLoaiToaVaoCBB() {
        cbbLoaiToa.removeAllItems();
        try {
            ResultSet rs = LopKetNoi.select("select maLoaiToa from LoaiToa order by heSo ASC");
            while (rs.next()) {
                cbbLoaiToa.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println("load ds loai toa vao cbb that bai");
        }
    }

    private void kiemTraSoChoNgoi() {
        if (jtfSoChoNgoi.getText().trim().equals("")) {
            jlbSoChoNgoi.setText("Không được để trống");
        } else {
            try {
                int soChoNgoi = Integer.parseInt(jtfSoChoNgoi.getText().trim());
                if (soChoNgoi <= 20 || soChoNgoi >= 50) {
                    jlbSoChoNgoi.setText("Số chỗ ngồi từ 20 đến 50 chỗ");
                } else {
                    if (soChoNgoi % 2 != 0) {
                        jlbSoChoNgoi.setText("Số chỗ ngồi phải chia hết cho 2");
                    } else {
                        jlbSoChoNgoi.setText(" ");
                    }
                }
            } catch (Exception e) {
                jlbSoChoNgoi.setText("Phải là một số nguyên");
            }
        }
    }

    private boolean kiemTraThemToa() {
        //kiem tra ma toa
        if (jtfMaToa.getText().trim().equals("")) {
            jlbMaToa.setText("Không được để trống");
        } else {
            try {
                ResultSet rs = LopKetNoi.select("select maToa from Toa where maToa", jtfMaToa.getText().trim());
                if (rs.next()) {
                    jlbMaToa.setText("Mã toa đã tồn tại");
                } else {
                    jlbMaToa.setText(" ");
                }

            } catch (Exception e) {
                System.out.println("Kiem tra ma toa that bai");
            }
        }

        // kiem tra soChoNgoi phải là số chia hết cho mấy đó
        kiemTraSoChoNgoi();
        if (jlbMaToa.getText().equals(" ") && jlbSoChoNgoi.getText().equals(" ")) {
            return true;
        } else {
            return false;
        }

    }

    private boolean themToa() {
        if (kiemTraThemToa()) {
            LopKetNoi.update("insert into Toa values(?,?,?)", jtfMaToa.getText().trim(),
                    Integer.parseInt(jtfSoChoNgoi.getText().trim()), cbbLoaiToa.getSelectedItem().toString());
            tbmToa.addRow(new Object[]{jtfMaToa.getText().trim(),
                Integer.parseInt(jtfSoChoNgoi.getText().trim()), cbbLoaiToa.getSelectedItem().toString()});

            // di chuyen den hang cuoi trong bang
            int hangCuoi = jtbToa.getRowCount();
            jtbToa.scrollRectToVisible(jtbToa.getCellRect(hangCuoi - 1, 0, true));// di chuyen bang den row cuoi
            jtbToa.clearSelection();
            jtbToa.setRowSelectionInterval(hangCuoi - 1, hangCuoi - 1);
            return true;
        } else {
            return false;
        }

    }

    private boolean suaToa() {
        kiemTraSoChoNgoi();
        if (jlbSoChoNgoi.getText().equals(" ")) {
            String maToa = jtfMaToa.getText().trim();
            int soChoNgoi = Integer.parseInt(jtfSoChoNgoi.getText().trim());
            String maLoaiToa = cbbLoaiToa.getSelectedItem().toString();
            LopKetNoi.update("update Toa set soChoNgoi = ?, maLoaiToa = ? where maToa = ?", soChoNgoi,
                    maLoaiToa, maToa);
            jtbToa.setValueAt(maToa, hangDangChonToa, 0);
            jtbToa.setValueAt(soChoNgoi, hangDangChonToa, 1);
            jtbToa.setValueAt(maLoaiToa, hangDangChonToa, 2);
        } else {
            return false;
        }
        return true;
    }

    private void thongTinToa() {
        String maToa = jtbToa.getValueAt(hangDangChonToa, 0).toString();
        String soChoNgoi = jtbToa.getValueAt(hangDangChonToa, 1).toString();
        String maLoaiToa = jtbToa.getValueAt(hangDangChonToa, 2).toString();
        jtfMaToa.setText(maToa);
        jtfSoChoNgoi.setText(soChoNgoi);
        cbbLoaiToa.setSelectedItem(maLoaiToa);
    }

    private void setRongCacTruongToa() {
        jtfMaToa.setText("");
        jtfSoChoNgoi.setText("20");
        if (cbbLoaiToa.getItemCount() != 0) {
            cbbLoaiToa.setSelectedIndex(0);
        }
    }

    private void tatThongBaoToa() {
        jlbMaToa.setText(" ");
        jlbSoChoNgoi.setText(" ");
        jlbLoaiToa.setText(" ");
    }

    private void hienCacTruongToa() {
        jtfMaToa.setEditable(true);
        jtfSoChoNgoi.setEditable(true);
        cbbLoaiToa.setEditable(true);
    }

    private void anCacTruongToa() {
        jtfMaToa.setEditable(false);
        jtfSoChoNgoi.setEditable(false);
        cbbLoaiToa.setEditable(false);
    }

    private void hienThiDialogToa(String loai) {
        setRongCacTruongToa();
        hienCacTruongToa();
        tatThongBaoToa();
        if (loai.equals(them)) {
            loadDSLoaiToaVaoCBB();
        } else if (loai.equals(sua)) {
            jtfMaToa.setText(jtbToa.getValueAt(hangDangChonToa, 0) + "");
            jtfMaToa.setEditable(false);
            jtfSoChoNgoi.setText(jtbToa.getValueAt(hangDangChonToa, 1) + "");
            loadDSLoaiToaVaoCBB();
            cbbLoaiToa.setSelectedItem(jtbToa.getValueAt(hangDangChonToa, 2) + "");
        } else if (loai.equals(thongTin)) {
            thongTinToa();
        }
        jlbTenDialogToa.setText(loai);
        jdlToa.setLocationRelativeTo(this);
        jdlToa.setVisible(true);
    }
    //=========================================================================================================

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaLoaiToa;
    private javax.swing.JButton btnSuaToa;
    private javax.swing.JButton btnThemLoaiToa;
    private javax.swing.JButton btnThemToa;
    private javax.swing.JButton btnThongTinLoaiToa;
    private javax.swing.JButton btnThongTinToa;
    private javax.swing.JButton btnTroVeLoaiToa;
    private javax.swing.JButton btnTroVeToa;
    private javax.swing.JButton btnXacNhanLoaiToa;
    private javax.swing.JButton btnXacNhanToa;
    private javax.swing.JButton btnXoaLoaiToa;
    private javax.swing.JButton btnXoaToa;
    private javax.swing.JComboBox<String> cbbLoaiToa;
    private javax.swing.JComboBox<String> cbbSapXepLoaiToa;
    private javax.swing.JComboBox<String> cbbSapXepToa;
    private javax.swing.JComboBox<String> cbbTimKiemLoaiToa;
    private javax.swing.JComboBox<String> cbbTimKiemToa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jdlLoaiToa;
    private javax.swing.JDialog jdlToa;
    private javax.swing.JLabel jlbHeSo;
    private javax.swing.JLabel jlbLoaiToa;
    private javax.swing.JLabel jlbMaLoaiToa;
    private javax.swing.JLabel jlbMaToa;
    private javax.swing.JLabel jlbSoChoNgoi;
    private javax.swing.JLabel jlbTenDialogLoaiToa;
    private javax.swing.JLabel jlbTenDialogToa;
    private javax.swing.JPanel jpnLoaiToa;
    private javax.swing.JPanel jpnToa;
    private javax.swing.JTable jtbLoaiToa;
    private javax.swing.JTable jtbToa;
    private javax.swing.JTextField jtfHeSo;
    private javax.swing.JTextField jtfHeSoLoaiToa;
    private javax.swing.JTextField jtfMaLoaiToa;
    private javax.swing.JTextField jtfMaToa;
    private javax.swing.JTextField jtfSoChoNgoi;
    private javax.swing.JTextField jtfTimKiemLoaiToa;
    private javax.swing.JTextField jtfTimKiemToa;
    // End of variables declaration//GEN-END:variables
}
