/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.quanlilotrinh;

import DungChung.StringDungChung;
import connectSQL.LopKetNoi;
import controller.ChuyenManHinhView;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import module.Chuyen;
import module.ThoiGianHoatDong;
import moduledao.ChuyenDao;
import moduledao.ThoiGianHoatDongDao;
import view.JPanelQuanLiLoTrinh;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanelChuyen extends javax.swing.JPanel {
    
    private float vanToc = 60;
    private ThoiGianHoatDongDao thoiGianDao;
    private DefaultTableModel tbmThoiGian, tbmChuyen;
    //==================================
    private String thongTin = "THÔNG TIN";
    private String them = "THÊM";
    private String sua = "SỬA";
    //================================
    private int hangThoiGian = -1;
    private int hangChuyen = -1;
    private int thoiGianNghiTuyen = 1;// gio

    /**
     * Creates new form JPanelQuanLiChuyen
     */
    public JPanelChuyen() {
        initComponents();
        thoiGianDao = new ThoiGianHoatDongDao();
        tbmChuyen = (DefaultTableModel) jtbChuyen.getModel();
        ChuyenDao.loadDSChuyenVaoBang(LopKetNoi.select("select * from Chuyen"), tbmChuyen);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlThongTinThoiGian = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jlbTenDialog = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfMaThoiGian = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfTenThoiGian = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbMaThoiGian = new javax.swing.JLabel();
        jlbTenThoiGian = new javax.swing.JLabel();
        jlbNgayBatDau = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jlbNgayKetThuc = new javax.swing.JLabel();
        btnXacNhanThoiGian = new javax.swing.JButton();
        jdcNgayBatDau = new com.toedter.calendar.JDateChooser();
        jdcNgayKetThuc = new com.toedter.calendar.JDateChooser();
        jdlThongTinChuyen = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jlbTenDialogChuyen = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfMaChuyen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnXacNhanChuyen = new javax.swing.JButton();
        jlbLoiMaChuyen = new javax.swing.JLabel();
        cbbMaTau = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cbbMaTuyen = new javax.swing.JComboBox<>();
        btnTramDiQua = new javax.swing.JButton();
        jlbNgayHoatDong = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbbGioKhoiHanh = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        dpNgayKhoiHanh = new com.github.lgooddatepicker.components.DatePicker();
        cbbNgayHD = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jlbLoTrinhTuyen = new javax.swing.JLabel();
        dtpLuotVe = new com.github.lgooddatepicker.components.DateTimePicker();
        btnXacNhanLoTrinh = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jlbLoiLuotDi = new javax.swing.JLabel();
        jlbLoiMaTau = new javax.swing.JLabel();
        jlbLoiMaTuyen = new javax.swing.JLabel();
        jlbLoiNgayHoatDong = new javax.swing.JLabel();
        jdlLichTrinh = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbLichTrinh = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbChuyen = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        cbbTiemKiem = new javax.swing.JComboBox<>();
        cbbSapXep = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnThongTIn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jdlThongTinThoiGian.setMinimumSize(new java.awt.Dimension(500, 511));

        jlbTenDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenDialog.setText("THÔNG TIN CHI TIẾT");
        jlbTenDialog.setBackground(new java.awt.Color(102, 255, 255));
        jlbTenDialog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setText("MÃ:");
        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jtfMaThoiGian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setText("TÊN: ");
        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jtfTenThoiGian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setText("NGÀY BẮT ĐẦU:");
        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabel7.setText("NGÀY KẾT THÚC:");
        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jlbMaThoiGian.setText("abc");
        jlbMaThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        jlbMaThoiGian.setForeground(new java.awt.Color(255, 51, 51));

        jlbTenThoiGian.setText("abc");
        jlbTenThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        jlbTenThoiGian.setForeground(new java.awt.Color(255, 51, 51));

        jlbNgayBatDau.setText("abc");
        jlbNgayBatDau.setBackground(new java.awt.Color(255, 255, 255));
        jlbNgayBatDau.setForeground(new java.awt.Color(255, 51, 51));

        jLabel17.setText("Định dạng: dd/MM/yyyy");

        jLabel18.setText("Định dạng: dd/MM/yyyy");

        jlbNgayKetThuc.setText("abc");
        jlbNgayKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        jlbNgayKetThuc.setForeground(new java.awt.Color(255, 51, 51));

        btnXacNhanThoiGian.setText("XÁC NHẬN");
        btnXacNhanThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanThoiGian.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhanThoiGian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanThoiGianActionPerformed(evt);
            }
        });

        jdcNgayBatDau.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayBatDau.setDateFormatString("dd/MM/yyyy");
        jdcNgayBatDau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jdcNgayKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayKetThuc.setDateFormatString("dd/MM/yyyy");
        jdcNgayKetThuc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTenDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbTenThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbMaThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfMaThoiGian)
                            .addComponent(jtfTenThoiGian)
                            .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnXacNhanThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlbTenDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfMaThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMaThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtfTenThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTenThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNgayBatDau)
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNgayKetThuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnXacNhanThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout jdlThongTinThoiGianLayout = new javax.swing.GroupLayout(jdlThongTinThoiGian.getContentPane());
        jdlThongTinThoiGian.getContentPane().setLayout(jdlThongTinThoiGianLayout);
        jdlThongTinThoiGianLayout.setHorizontalGroup(
            jdlThongTinThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdlThongTinThoiGianLayout.setVerticalGroup(
            jdlThongTinThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jdlThongTinChuyen.setMinimumSize(new java.awt.Dimension(545, 604));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jlbTenDialogChuyen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenDialogChuyen.setText("THÔNG TIN CHI TIẾT");
        jlbTenDialogChuyen.setBackground(new java.awt.Color(102, 255, 255));
        jlbTenDialogChuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel10.setText("MÃ CHUYẾN:");
        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jtfMaChuyen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setText("MÃ TUYẾN:");
        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        btnXacNhanChuyen.setText("XÁC NHẬN");
        btnXacNhanChuyen.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanChuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhanChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanChuyenActionPerformed(evt);
            }
        });

        jlbLoiMaChuyen.setText("a");
        jlbLoiMaChuyen.setBackground(new java.awt.Color(255, 255, 255));
        jlbLoiMaChuyen.setForeground(new java.awt.Color(255, 51, 51));

        cbbMaTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaTauActionPerformed(evt);
            }
        });

        jLabel27.setText("MÃ TÀU:");
        jLabel27.setBackground(new java.awt.Color(204, 204, 204));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        cbbMaTuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaTuyenActionPerformed(evt);
            }
        });

        btnTramDiQua.setText("XEM TRẠM ĐI QUA");
        btnTramDiQua.setBackground(new java.awt.Color(255, 255, 255));

        jlbNgayHoatDong.setText("ngay");

        jLabel12.setText("LƯỢT ĐI:");
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        cbbGioKhoiHanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "15", "20" }));
        cbbGioKhoiHanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGioKhoiHanhActionPerformed(evt);
            }
        });

        jLabel13.setText("giờ");

        dpNgayKhoiHanh.setBackground(new java.awt.Color(255, 255, 255));

        cbbNgayHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNgayHDActionPerformed(evt);
            }
        });

        jLabel26.setText("NGÀY HOẠT ĐỘNG:");
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel20.setText("LƯỢT VỀ:");
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jlbLoTrinhTuyen.setText("lo trinh tuyen");

        dtpLuotVe.setBackground(new java.awt.Color(255, 255, 255));
        dtpLuotVe.setEnabled(false);

        btnXacNhanLoTrinh.setText("XÁC NHẬN LỘ TRÌNH");
        btnXacNhanLoTrinh.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanLoTrinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanLoTrinhActionPerformed(evt);
            }
        });

        btnHuy.setText("HỦY ");
        btnHuy.setBackground(new java.awt.Color(255, 255, 255));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel14.setText("BẤM XÁC NHẬN ĐỂ CHỌN TÀU");
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jlbLoiLuotDi.setText("jlbLuotDi");
        jlbLoiLuotDi.setForeground(new java.awt.Color(255, 0, 0));

        jlbLoiMaTau.setText("jLabel15");

        jlbLoiMaTuyen.setText("jLabel16");

        jlbLoiNgayHoatDong.setText("jLabel19");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTenDialogChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel20)
                    .addComponent(jLabel10)
                    .addComponent(jLabel26)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbNgayHD, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbLoiMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtpLuotVe, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbNgayHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbbMaTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTramDiQua))
                            .addComponent(cbbMaTau, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlbLoiMaTuyen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbLoTrinhTuyen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlbLoiNgayHoatDong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbLoiLuotDi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(dpNgayKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbGioKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnXacNhanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(144, 144, 144)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlbLoiMaTau, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(btnXacNhanLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jlbTenDialogChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbLoiMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbbMaTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTramDiQua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbLoTrinhTuyen)
                .addGap(3, 3, 3)
                .addComponent(jlbLoiMaTuyen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbNgayHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNgayHoatDong)
                .addGap(5, 5, 5)
                .addComponent(jlbLoiNgayHoatDong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dpNgayKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbGioKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbLoiLuotDi)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(dtpLuotVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhanLoTrinh)
                    .addComponent(btnHuy)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cbbMaTau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbLoiMaTau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnXacNhanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout jdlThongTinChuyenLayout = new javax.swing.GroupLayout(jdlThongTinChuyen.getContentPane());
        jdlThongTinChuyen.getContentPane().setLayout(jdlThongTinChuyenLayout);
        jdlThongTinChuyenLayout.setHorizontalGroup(
            jdlThongTinChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlThongTinChuyenLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdlThongTinChuyenLayout.setVerticalGroup(
            jdlThongTinChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jdlLichTrinh.setMinimumSize(new java.awt.Dimension(492, 278));

        jtbLichTrinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LỊCH TRÌNH"
            }
        ));
        jScrollPane2.setViewportView(jtbLichTrinh);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THÔNG TIN LỊCH TRÌNH TÀU");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );

        javax.swing.GroupLayout jdlLichTrinhLayout = new javax.swing.GroupLayout(jdlLichTrinh.getContentPane());
        jdlLichTrinh.getContentPane().setLayout(jdlLichTrinhLayout);
        jdlLichTrinhLayout.setHorizontalGroup(
            jdlLichTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlLichTrinhLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdlLichTrinhLayout.setVerticalGroup(
            jdlLichTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlLichTrinhLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN BẢNG CHUYẾN");
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtbChuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ CHUYẾN", "MÃ TÀU", "MÃ TUYẾN", "LỘ TRÌNH(GIỜ)", "CHU KÌ(NGÀY)", "THỜI GIAN KH", "LƯỢT ĐI", "LƯỢT VỀ", "NGÀY HOẠT ĐỘNG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbChuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbChuyen.setGridColor(new java.awt.Color(255, 255, 255));
        jtbChuyen.setRowHeight(25);
        jtbChuyen.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jtbChuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbChuyenMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbChuyenMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbChuyen);
        if (jtbChuyen.getColumnModel().getColumnCount() > 0) {
            jtbChuyen.getColumnModel().getColumn(0).setResizable(false);
            jtbChuyen.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtbChuyen.getColumnModel().getColumn(1).setResizable(false);
            jtbChuyen.getColumnModel().getColumn(2).setResizable(false);
            jtbChuyen.getColumnModel().getColumn(3).setResizable(false);
            jtbChuyen.getColumnModel().getColumn(4).setResizable(false);
            jtbChuyen.getColumnModel().getColumn(5).setResizable(false);
            jtbChuyen.getColumnModel().getColumn(6).setResizable(false);
            jtbChuyen.getColumnModel().getColumn(7).setResizable(false);
            jtbChuyen.getColumnModel().getColumn(8).setResizable(false);
            jtbChuyen.getColumnModel().getColumn(8).setPreferredWidth(150);
        }

        jLabel5.setText("Chức năng");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnThem.setText("THÊM");
        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("SỬA");
        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("XÓA");
        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel8.setText("Tìm kiếm:");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemKeyReleased(evt);
            }
        });

        cbbTiemKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cbbSapXep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSapXepActionPerformed(evt);
            }
        });

        jLabel9.setText("Sắp xếp:");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnThongTIn.setText("THÔNG TIN");
        btnThongTIn.setBackground(new java.awt.Color(255, 255, 255));
        btnThongTIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongTIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(287, 287, 287))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(59, 59, 59)
                                        .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addGap(74, 74, 74)
                                        .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                        .addGap(64, 64, 64)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbTiemKiem, 0, 151, Short.MAX_VALUE)
                                        .addGap(158, 158, 158)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbSapXep, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(btnThongTIn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))))
                        .addGap(32, 32, 32))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnThongTIn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbSapXep)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfTimKiem)
                            .addComponent(cbbTiemKiem))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtbChuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbChuyenMouseClicked
        // TODO add your handling code here:
        hangChuyen = jtbChuyen.getSelectedRow();
    }//GEN-LAST:event_jtbChuyenMouseClicked

    private void jtbChuyenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbChuyenMousePressed
        // TODO add your handling code here:
        hangChuyen = jtbChuyen.getSelectedRow();
        if (hangChuyen != -1) {
            if (evt.getButton() == MouseEvent.BUTTON3) {
                hienThiDialogChuyen(thongTin);
            }
        }
    }//GEN-LAST:event_jtbChuyenMousePressed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        hienThiDialogChuyen(them);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (hangChuyen < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 dòng trong bảng");
        } else {
            hienThiDialogChuyen(sua);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (hangChuyen < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 hàng trong bảng");
            
        } else {
            int input = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (input == JOptionPane.YES_OPTION) {
                String maChuyen = jtbChuyen.getValueAt(hangChuyen, 0).toString();
                boolean kt = ChuyenDao.xoaChuyenTrongDB(maChuyen);
                if (kt) {
                    ChuyenDao.xoaChuyenKhoiBang(hangChuyen, tbmChuyen);
                    hangChuyen = -1;
                    jtbChuyen.clearSelection();
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể xóa vì có tàu đang chạy trên tuyến này");
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jtfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKeyReleased
        // TODO add your handling code here:

//        if (cbbTiemKiem.getSelectedIndex() == 0) {// tim kiem theo ma tuyen
//            String maTuyen = jtfTimKiem.getText().trim();
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen where maTuyen like ?",
//                "%" + maTuyen + "%"), tbmBangTuyen);
//        } else {// tim kiem theo ten tuyen
//            String tenTuyen = jtfTimKiem.getText().trim();
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen where tenTuyen like ?",
//                "%" + tenTuyen + "%"), tbmBangTuyen);
//        }
    }//GEN-LAST:event_jtfTimKiemKeyReleased

    private void cbbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSapXepActionPerformed
        // TODO add your handling code here:
//        if (cbbSapXep.getSelectedIndex() == 0) {// sap xep ten tuyen tu a - z
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen order by tentuyen ASC"), tbmBangTuyen);
//        } else {
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen order by tentuyen DESC"), tbmBangTuyen);
//        }
    }//GEN-LAST:event_cbbSapXepActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiLoTrinh()).change();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThongTInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTInActionPerformed
        // TODO add your handling code here:
        if (hangChuyen == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hàng trong bảng");
        } else
            hienThiDialogChuyen(thongTin);
    }//GEN-LAST:event_btnThongTInActionPerformed

    private void btnXacNhanThoiGianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanThoiGianActionPerformed
        // TODO add your handling code here:
        String loai = jlbTenDialog.getText();
        xuLiXacNhanChuyen(loai);
    }//GEN-LAST:event_btnXacNhanThoiGianActionPerformed

    private void jtfMaTuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaTuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMaTuyenActionPerformed

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        //kiểm tra tàu thích hợp
        capNhatLuotVe();

    }//GEN-LAST:event_jPanel3MouseEntered

    private void cbbGioKhoiHanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGioKhoiHanhActionPerformed
        // TODO add your handling code here:
        if (cbbGioKhoiHanh.getItemCount() != 0) {
            int gio = Integer.parseInt(cbbGioKhoiHanh.getSelectedItem().toString());
            try {
                LocalDate ngayKhoiHanh = dpNgayKhoiHanh.getDate();
                LocalDateTime thoiGianKhoiHanh = ngayKhoiHanh.atTime(gio, 0);
                dtpLuotVe.setDateTimePermissive(ChuyenDao.getThoiGianKT(cbbMaTuyen.getSelectedItem().toString(),
                        thoiGianKhoiHanh));
            } catch (Exception e) {
                System.out.println("cbb tgkh loi");
            }
            
        }
    }//GEN-LAST:event_cbbGioKhoiHanhActionPerformed

    private void cbbMaTuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaTuyenActionPerformed
        // TODO add your handling code here:
        if (cbbMaTuyen.getItemCount() != 0) {
            int gio = ChuyenDao.layLoTrinhTuyen(cbbMaTuyen.getSelectedItem().toString());
            int chuKi = ChuyenDao.layChuKiTuyen(cbbMaTuyen.getSelectedItem().toString());
            jlbLoTrinhTuyen.setText("Lộ trình tuyến: " + gio + "giờ" + "\n-Chu kì tuyến: " + chuKi + "ngày");
        }
    }//GEN-LAST:event_cbbMaTuyenActionPerformed

    private void btnXacNhanChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanChuyenActionPerformed
        // TODO add your handling code here:
        xuLiXacNhanChuyen(jlbTenDialogChuyen.getText());
    }//GEN-LAST:event_btnXacNhanChuyenActionPerformed

    private void cbbNgayHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNgayHDActionPerformed
        // TODO add your handling code here:
        capNhatCBBNgayHD();
    }//GEN-LAST:event_cbbNgayHDActionPerformed

    private void cbbMaTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaTauActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cbbMaTauActionPerformed

    private void btnXacNhanLoTrinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanLoTrinhActionPerformed
        // TODO add your handling code here:
        tatTatCaTruongChuyen();
        if (cbbMaTuyen.getItemCount() != 0 && cbbNgayHD.getItemCount() != 0) {
            try {
                LocalDate ngayKH = dpNgayKhoiHanh.getDate();
                cbbMaTau.removeAllItems();
                String maTuyen = cbbMaTuyen.getSelectedItem().toString();
                String tenNgayHoatDong = cbbNgayHD.getSelectedItem().toString();
                int gio = Integer.parseInt(cbbGioKhoiHanh.getSelectedItem().toString());
                LocalDateTime tgKhoiHanh = dpNgayKhoiHanh.getDate().atTime(gio, 0);
                System.out.println("Vao btn xac nhan lich trinh tuyen");
                if (jlbTenDialogChuyen.getText().equals(sua)) {
                    tgKhoiHanh.plusMinutes(1);
                }
                ArrayList<String> dsTau = ChuyenDao.layTauHopLi(maTuyen, tenNgayHoatDong, tgKhoiHanh);
                for (String s : dsTau) {
                    cbbMaTau.addItem(s);
                }
                
            } catch (Exception e) {
            }
        }
        // neu la sua chuyen thi them tau cua chuyen do
        if (jlbTenDialogChuyen.getText().equals(sua)) {
            try {
                ResultSet rs = LopKetNoi.select("select maTau from Chuyen where maChuyen = ?", jtfMaChuyen.getText());
                if (rs.next()) {
                    cbbMaTau.addItem(rs.getString(1));
                }
            } catch (Exception e) {
            }
            
        }
        btnXacNhanLoTrinh.setEnabled(false);
        cbbMaTau.setEnabled(true);
        btnHuy.setEnabled(true);
    }//GEN-LAST:event_btnXacNhanLoTrinhActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        btnHuy.setEnabled(false);
        batTatCaTruongChuyen();
        cbbMaTau.removeAllItems();
        cbbMaTau.setEnabled(false);
        btnXacNhanLoTrinh.setEnabled(true);
    }//GEN-LAST:event_btnHuyActionPerformed

//    private void capNhatCBBMaTau() {
//        cbbMaTau.removeAllItems();
//        try {
//            ResultSet rs = LopKetNoi.select("select ", args);
//        } catch (Exception e) {
//        }
//    }
    //==============================================================================================
    //CHUYEN
//    private boolean kiemTraTGKH(){// nếu cùng tuyến thì xem xét có trùng thời gian khỏi hành không
//        
//        
//    }
//===============================================================================================
    private void capNhatLuotVe() {// tu luot di
        if (cbbMaTuyen.getItemCount() != 0) {
            try {
                int gio = Integer.parseInt(cbbGioKhoiHanh.getSelectedItem().toString());
                LocalDateTime luotDi = dpNgayKhoiHanh.getDate().atTime(gio, 0);
                String maTuyen = cbbMaTuyen.getSelectedItem().toString();
                LocalDateTime luotVe = luotDi.plusDays(ChuyenDao.layChuKiTuyen(maTuyen) / 2);
                dtpLuotVe.setDateTimePermissive(luotVe);
            } catch (Exception e) {
                System.out.println("Chua co ngay");
            }
        }
        
    }
    
    private void capNhatCBBNgayHD() {
        if (cbbNgayHD.getItemCount() != 0) {
            String tenNgayHoatDong = cbbNgayHD.getSelectedItem().toString();
            ArrayList<LocalDate> ngayBDKT = layNgayBDVaKT(tenNgayHoatDong);
            dpNgayKhoiHanh.setDate(ngayBDKT.get(0));
            jlbNgayHoatDong.setText("Từ ngày " + ngayBDKT.get(0) + " dến ngày " + ngayBDKT.get(1));
//        capNhatNgayHoatDong();
        }
    }
    
    private int layGioTuCbb() {
        
        if (cbbGioKhoiHanh.getItemCount() != 0) {
            int gio = Integer.parseInt(cbbGioKhoiHanh.getSelectedItem().toString());
            return gio;
        }
        return 0;
    }
    
    private void capNhatNgayHoatDong() {// gom jlb ngay hoat dong, dpNgayKhoiHanh, jlbNgayKhoiHanh, chu ki tau, thoiGianDen
        if (cbbNgayHD.getItemCount() != 0) {
            String tenNgayHoatDong = cbbNgayHD.getSelectedItem().toString();
            ArrayList<LocalDate> ngayBDKT = layNgayBDVaKT(tenNgayHoatDong);
//            dpNgayKhoiHanh.setDate(ngayBDKT.get(0));

        }
    }
    
    private int layChuKiTuyen() {/// trả về ngày
        int chuKiTuyen = -1;
        if (cbbMaTuyen.getItemCount() != 0) {
            String maTuyen = cbbMaTuyen.getSelectedItem().toString();
            int gio = 0;
            ResultSet rs = LopKetNoi.select("select max(thoiGianDen) from TuyenDiQuaTram where maTuyen = ?", maTuyen);
            try {
                if (rs.next()) {
                    gio = rs.getInt(1);
                }
            } catch (Exception e) {
                System.out.println("get thoi gian chay tuyen that bai");
            }
            // tinh chu ki

            chuKiTuyen = (int) Math.ceil((gio * 2 + 2 * thoiGianNghiTuyen) / 24.0);// ngày

        }
        return chuKiTuyen;
    }
    
    private void capNhatThongTin() {// 
//        if (cbbMaTuyen.getItemCount() != 0) {
//            int chuKiTuyen = Integer.parseInt(jlbChuKiTuyen.getText());
//            String maTuyen = cbbMaTuyen.getSelectedItem().toString();
//            LocalDate ngayKhoiHanh = dpNgayKhoiHanh.getDate();
//            jlbNgayKhoiHanh.setText(ngayKhoiHanh + ", "
//                    + ngayKhoiHanh.plusDays(chuKiTuyen) + ", " + ngayKhoiHanh.plusDays(chuKiTuyen * 2) + ",...");
//            jlbChuKiTau.setText("Tuyến khởi hành đúng " + layGioTuCbb() + " giờ mỗi " + chuKiTuyen + " ngày");
//            LocalDateTime thoiGianKH = ngayKhoiHanh.atTime(layGioTuCbb(), 0);
//            dtpThoiGianDen.setDateTimePermissive(ChuyenDao.getThoiGianKT(maTuyen, thoiGianKH));
//        }
    }
    
    private ArrayList<LocalDate> layNgayBDVaKT(String tenNgayHoatDong) {
        ArrayList<LocalDate> ngayBDKT = new ArrayList<>();
        try {
            ResultSet rs = LopKetNoi.select("select ngayBatDau, ngayKetThuc from NgayHoatDong where "
                    + "tenNgayHoatDong = ?", tenNgayHoatDong);
            if (rs.next()) {
                ngayBDKT.add(rs.getDate(1).toLocalDate());
                ngayBDKT.add(rs.getDate(2).toLocalDate());
            }
        } catch (Exception e) {
            System.out.println("get ngay bd kt that bai");
        }
        return ngayBDKT;
    }
    
    private void napNgayHoatDongVaoCBB() {
        cbbNgayHD.removeAllItems();
        try {
            ResultSet rs = LopKetNoi.select("select tenNgayHoatDong from NgayHoatDong");
            while (rs.next()) {
                cbbNgayHD.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
        
    }
    
    private void loadMaTuyenVaoCBB() {
        cbbMaTuyen.removeAllItems();
        try {
            ResultSet rs = LopKetNoi.select("select maTuyen from Tuyen");
            while (rs.next()) {
                cbbMaTuyen.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println("Load ma tuyen vao cbb that bai");
        }
        
    }
    
    private void kiemTraMaChuyen() {
        String maChuyen = jtfMaChuyen.getText().trim();
        if (maChuyen.equals("")) {
            jlbLoiMaChuyen.setText("Không được để trống");
        } else {
            if (ChuyenDao.kiemTraMaTrung(maChuyen)) {
                jlbLoiMaChuyen.setText(" ");
            } else {
                jlbLoiMaChuyen.setText("Mã bị trùng");
            }
        }
    }
    
    private void kiemTraMaTau() {
        if (cbbMaTau.getItemCount() == 0) {
            jlbLoiMaTau.setText("Hiện chưa có tàu");
        } else {
            jlbLoiMaTau.setText(" ");
        }
    }
    
    private void kiemTraMaTuyen() {
        if (cbbMaTuyen.getItemCount() == 0) {
            jlbLoiMaTuyen.setText("Hiện chưa có tuyến");
        } else {
            jlbLoiMaTuyen.setText(" ");
        }
    }
    
    private void kiemTraThoiGianKH() {
        try {
            LocalDateTime thoiGianKH = dpNgayKhoiHanh.getDate().atTime(Integer.parseInt(
                    cbbGioKhoiHanh.getSelectedItem().toString()), 0);
            ArrayList<LocalDate> ngayBDKT = layNgayBDVaKT(cbbNgayHD.getSelectedItem().toString());
            if (thoiGianKH.toLocalDate().compareTo(ngayBDKT.get(0)) < 0) {
                jlbNgayHoatDong.setText("Ngày khởi hành phải nằm trong ngày hoạt động");
            } else {
                jlbNgayHoatDong.setText(" ");
            }
        } catch (Exception e) {
            jlbNgayHoatDong.setText("Vui lòng chọn đầy đủ ngày và giờ");
        }
    }
    
    private void kiemTraNgayHoatDong() {
        if (cbbNgayHD.getItemCount() == 0) {
            jlbLoiNgayHoatDong.setText("Chưa có ngày hoạt động");
        } else {
            jlbLoiNgayHoatDong.setText(" ");
        }
    }
    
    private boolean kiemTraDuLieuHopLeChuyen() {
        // mã không cách và không được trùng
        if (jlbTenDialogChuyen.getText().equals(them)) {
            kiemTraMaChuyen();
        }
        kiemTraMaTau();
        kiemTraMaTuyen();
        kiemTraThoiGianKH();
        if (jlbLoiMaChuyen.getText().equals(" ") && jlbNgayHoatDong.getText().equals(" ")
                && jlbLoiMaTau.getText().equals(" ") && jlbLoiMaTuyen.getText().equals(" ")) {
            return true;
        } else {
            return false;
        }
        
    }

//    private void loadThoiGianVaoCBB(ResultSet rs, JComboBox cbb) {
//        cbb.removeAllItems();
//        try {
//            while (rs.next()) {
//                String ngayBD = StringDungChung.DateSangString(rs.getDate(1), "dd/MM/yyyy");
//                String ngayKT = StringDungChung.DateSangString(rs.getDate(2), "dd/MM/yyyy");
//                String tam = ngayBD + " đến " + ngayKT;
//                cbb.addItem(tam);
//            }
//        } catch (Exception e) {
//        }
//    }
    private Chuyen getChuyenTuJDL() {
        String maChuyen = jtfMaChuyen.getText().trim();
        String maTau = cbbMaTau.getSelectedItem().toString();
        String maTuyen = cbbMaTuyen.getSelectedItem().toString();
        String tenNgayHoatDong = cbbNgayHD.getSelectedItem().toString();
        int gioKH = Integer.parseInt(cbbGioKhoiHanh.getSelectedItem().toString());
        LocalDate ngayKH = dpNgayKhoiHanh.getDate();
        Chuyen chuyen = new Chuyen(maChuyen, maTau, maTuyen, tenNgayHoatDong, gioKH, ngayKH);
        return chuyen;
        
    }
    
    private void themChuyenVaoBang() {

        Chuyen chuyen = getChuyenTuJDL();
        // them vao bang
        tbmChuyen.addRow(new Object[]{chuyen.getMa(), chuyen.getMaTau(), chuyen.getMaTuyen(),
            chuyen.getLoTrinhTuyen(), chuyen.getChuKiTuyen(), chuyen.getGioKhoiHanh(), chuyen.getLuotDi(),
            chuyen.getLuotVe(), chuyen.getNgayHoatDong()});
        int hangCuoi = jtbChuyen.getRowCount();
        jtbChuyen.scrollRectToVisible(jtbChuyen.getCellRect(hangCuoi - 1, 0, true));
        jtbChuyen.clearSelection();
        jtbChuyen.setRowSelectionInterval(hangCuoi - 1, hangCuoi - 1);
    }
    
    private boolean themChuyen() {
        if (kiemTraDuLieuHopLeChuyen()) {
            Chuyen chuyen = getChuyenTuJDL();
            JOptionPane.showMessageDialog(jdlThongTinChuyen, "Thêm thành công");
            ChuyenDao.themChuyenVaoDB(chuyen);
            themChuyenVaoBang();
            return true;
        } else {
            return false;
        }
    }
    
    private void suaChuyenTrongBang() {
        Chuyen chuyen = getChuyenTuJDL();
        // them vao bang
        jtbChuyen.setValueAt(chuyen.getMaTau(), hangChuyen, 1);
        jtbChuyen.setValueAt(chuyen.getMaTuyen(), hangChuyen, 2);
        jtbChuyen.setValueAt(chuyen.getLoTrinhTuyen(), hangChuyen, 3);
        jtbChuyen.setValueAt(chuyen.getChuKiTuyen(), hangChuyen, 4);
        jtbChuyen.setValueAt(chuyen.getGioKhoiHanh(), hangChuyen, 5);
        jtbChuyen.setValueAt(chuyen.getLuotDi(), hangChuyen, 6);
        jtbChuyen.setValueAt(chuyen.getLuotVe(), hangChuyen, 7);
        jtbChuyen.setValueAt(chuyen.getNgayHoatDong(), hangChuyen, 8);
    }

    private boolean suaChuyen() {
        if (kiemTraDuLieuHopLeChuyen()) {
            Chuyen chuyen = getChuyenTuJDL();
            JOptionPane.showMessageDialog(jdlThongTinChuyen, "Sửa thành công");
            ChuyenDao.suaChuyenTrongDB(chuyen);
            suaChuyenTrongBang();
            return true;
        } else {
            return false;
        }
    }
    
    private boolean xoaChuyen() {
        if (ChuyenDao.xoaChuyenTrongDB(jtbChuyen.getValueAt(hangThoiGian, 0).toString())) {
            ChuyenDao.xoaChuyenKhoiBang(hangChuyen, tbmChuyen);
            return true;
        } else {
            return false;
        }
        
    }
    
    private void setTatCaTruongRongChuyen() {
        jtfMaChuyen.setText("");
        cbbMaTau.removeAllItems();
        if (cbbMaTuyen.getItemCount() != 0) {
            cbbMaTuyen.setSelectedIndex(0);
        }
        dpNgayKhoiHanh.setDateToToday();
    }
    
    private void setTatCaThongBaoRongChuyen() {
        jlbLoiMaChuyen.setText(" ");
        jlbLoiNgayHoatDong.setText(" ");
        jlbLoiLuotDi.setText(" ");
        jlbLoiMaTau.setText(" ");
        jlbLoiMaTuyen.setText(" ");
    }
    
    private void batTatCaTruongChuyen() {
        jtfMaChuyen.setEditable(true);
        cbbMaTau.setEnabled(true);
        cbbMaTuyen.setEnabled(true);
        cbbMaTuyen.setEnabled(true);
        cbbNgayHD.setEnabled(true);
        dpNgayKhoiHanh.setEnabled(true);
        cbbGioKhoiHanh.setEnabled(true);
        
    }
    
    private void tatTatCaTruongChuyen() {
        jtfMaChuyen.setEditable(false);
        cbbMaTau.setEnabled(false);
        cbbMaTuyen.setEnabled(false);
        cbbMaTuyen.setEnabled(false);
        cbbNgayHD.setEnabled(false);
        dpNgayKhoiHanh.setEnabled(false);
        cbbGioKhoiHanh.setEnabled(false);
    }
    
    private void loadDSTauVaoCBB(JComboBox cbb) {
        cbb.removeAllItems();
        ArrayList<String> DS = ChuyenDao.getDSMaTau(LopKetNoi.select("select * from Tau"));
        for (String s : DS) {
            cbb.addItem(s);
        }
    }
    
    private void loadTramBDKTVaoCBB(JComboBox cbb) {
        cbb.removeAllItems();
        ArrayList<String> DS = ChuyenDao.getDSTramBDVaKetThuc(LopKetNoi.select("select * from Tuyen"));
        for (String s : DS) {
            cbb.addItem(s);
        }
    }
    
    private void napChuyenVaoDialog(String maChuyen) {
        try {
            ResultSet rs = LopKetNoi.select("select * from Chuyen where maChuyen = ?", maChuyen);
            if (rs.next()) {
                jtfMaChuyen.setText(rs.getString("maChuyen"));
                cbbMaTau.setSelectedItem(rs.getString("maTau"));
                cbbMaTuyen.setSelectedItem(rs.getString("maTuyen"));
                LocalDateTime thoiGianKH = rs.getTimestamp("thoiGianKhoiHanh").toLocalDateTime();
                dpNgayKhoiHanh.setDate(thoiGianKH.toLocalDate());
                int gio = thoiGianKH.toLocalTime().getHour();
                cbbGioKhoiHanh.setSelectedItem(gio + "");
                LocalDateTime thoiGianDen = ChuyenDao.getThoiGianKT(rs.getString("maTuyen"), thoiGianKH);
                dtpLuotVe.setDateTimePermissive(thoiGianDen);// bo rs.getString(5);
                try {
                    ResultSet rs1 = LopKetNoi.select("select ngayBatDau, ngayKetThuc from NgayHoatDong "
                            + "where tenNgayHoatDong = ?", rs.getString("tenNgayHoatDong"));
                    if (rs1.next()) {
                        jlbNgayHoatDong.setText(rs1.getDate(1) + " đến " + rs1.getDate(2));
                    }
                } catch (Exception e) {
                }
//                dpNgayBatDau.setDate(thoiGianKH.toLocalDate());
//                dpNgayKetThuc.setDate(rs.getDate("ngayKetThuc").toLocalDate());
            }
        } catch (Exception e) {
        }
        
    }
    
    private void hienThiDialogChuyen(String loai) {
        setTatCaTruongRongChuyen();
        setTatCaThongBaoRongChuyen();
        batTatCaTruongChuyen();
        if (loai.equals(thongTin)) {
            tatTatCaTruongChuyen();
            napChuyenVaoDialog(jtbChuyen.getValueAt(hangChuyen, 0).toString());
        } else if (loai.equals(them)) {
            cbbMaTau.setEnabled(false);
            btnHuy.setEnabled(false);
            loadMaTuyenVaoCBB();
            napNgayHoatDongVaoCBB();
        } else if (loai.equals(sua)) {
            jtfMaChuyen.setEditable(false);
            loadMaTuyenVaoCBB();
            napNgayHoatDongVaoCBB();
            napChuyenVaoDialog(jtbChuyen.getValueAt(hangChuyen, 0).toString());
        }
        jlbTenDialogChuyen.setText(loai);
        jdlThongTinChuyen.setLocationRelativeTo(this);
        jdlThongTinChuyen.setVisible(true);
    }
    
    private void xuLiXacNhanChuyen(String loai) {
        if (loai.equals(thongTin)) {
            jdlThongTinChuyen.dispose();
        } else if (loai.equals(them)) {
            if (themChuyen()) {
                setTatCaTruongRongChuyen();
                setTatCaThongBaoRongChuyen();
                batTatCaTruongChuyen();
                cbbMaTau.setEnabled(false);
                btnXacNhanLoTrinh.setEnabled(true);
                btnHuy.setEnabled(false);
                hangChuyen = jtbChuyen.getRowCount() - 1;
            } else {
                JOptionPane.showMessageDialog(jdlThongTinChuyen, "Thêm thất bại");
            }
        } else if (loai.equals(sua)) {
            if (suaChuyen()) {
                jdlThongTinChuyen.dispose();
            } else {
                JOptionPane.showMessageDialog(jdlThongTinChuyen, "Sửa thất bại");
            }
        }
    }

//============================================================================================
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThongTIn;
    private javax.swing.JButton btnTramDiQua;
    private javax.swing.JButton btnXacNhanChuyen;
    private javax.swing.JButton btnXacNhanLoTrinh;
    private javax.swing.JButton btnXacNhanThoiGian;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbGioKhoiHanh;
    private javax.swing.JComboBox<String> cbbMaTau;
    private javax.swing.JComboBox<String> cbbMaTuyen;
    private javax.swing.JComboBox<String> cbbNgayHD;
    private javax.swing.JComboBox<String> cbbSapXep;
    private javax.swing.JComboBox<String> cbbTiemKiem;
    private com.github.lgooddatepicker.components.DatePicker dpNgayKhoiHanh;
    private com.github.lgooddatepicker.components.DateTimePicker dtpLuotVe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JDateChooser jdcNgayBatDau;
    private com.toedter.calendar.JDateChooser jdcNgayKetThuc;
    private javax.swing.JDialog jdlLichTrinh;
    private javax.swing.JDialog jdlThongTinChuyen;
    private javax.swing.JDialog jdlThongTinThoiGian;
    private javax.swing.JLabel jlbLoTrinhTuyen;
    private javax.swing.JLabel jlbLoiLuotDi;
    private javax.swing.JLabel jlbLoiMaChuyen;
    private javax.swing.JLabel jlbLoiMaTau;
    private javax.swing.JLabel jlbLoiMaTuyen;
    private javax.swing.JLabel jlbLoiNgayHoatDong;
    private javax.swing.JLabel jlbMaThoiGian;
    private javax.swing.JLabel jlbNgayBatDau;
    private javax.swing.JLabel jlbNgayHoatDong;
    private javax.swing.JLabel jlbNgayKetThuc;
    private javax.swing.JLabel jlbTenDialog;
    private javax.swing.JLabel jlbTenDialogChuyen;
    private javax.swing.JLabel jlbTenThoiGian;
    private javax.swing.JTable jtbChuyen;
    private javax.swing.JTable jtbLichTrinh;
    private javax.swing.JTextField jtfMaChuyen;
    private javax.swing.JTextField jtfMaThoiGian;
    private javax.swing.JTextField jtfTenThoiGian;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables
}
